spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        ejb:
          interceptor: com.noya.rbac.common.interceptor.AutoSetIdInterceptor